#pragma once

#include "ABI.h"

namespace rrtmgp {

void interpolation_fpga(
    const int ncol,
    const int nlay,
    const int ngas,
    const int nflav,
    const int neta,
    const int npres,
    const int ntemp,
    const int flavor[20],
    const REAL press_ref_log[59],
    const REAL temp_ref[14],
    REAL press_ref_log_delta,
    REAL temp_ref_min,
    REAL temp_ref_delta,
    REAL press_ref_trop_log,
    const REAL vmr_ref[252],
    const REAL play[5376],
    const REAL tlay[5376],
    const REAL col_gas[48384],
    int jtemp[5376],
    REAL fmajor[430080],
    REAL fminor[215040],
    REAL col_mix[107520],
    BOOL tropo[5376],
    int jeta[107520],
    int jpress[5376]);

void combine_abs_and_rayleigh_fpga(
    const int ncol,
    const int nlay,
    const int ngpt,
    const REAL* tau_local,
    const REAL* tau_rayleigh,
    REAL* tau,
    REAL* ssa,
    REAL* g);

void compute_tau_rayleigh_fpga(
    const int ncol,
    const int nlay,
    const int nbnd,
    const int ngpt,
    const int ngas,
    const int nflav,
    const int neta,
    const int npres,
    const int ntemp,
    const int gpoint_flavor[448],
    const int gpoint_bands[224],
    const int band_lims_gpt[28],
    const REAL krayl[56448],
    int idx_h2o,
    const REAL col_dry[5376],
    const REAL col_gas[48384],
    const REAL fminor[193536],
    const int jeta[96768],
    const BOOL tropo[5376],
    const int jtemp[5376],
    REAL tau_rayleigh[1204224]);

void compute_tau_absorption_fpga(
    const int ncol,
    const int nlay,
    const int nband,
    const int ngpt,
    const int ngas,
    const int nflav,
    const int neta,
    const int npres,
    const int ntemp,
    const int nminorlower,
    const int nminorklower,
    const int nminorupper,
    const int nminorkupper,
    const int idx_h2o,
    const int gpoint_flavor[448],
    const int band_lims_gpt[28],
    const REAL kmajor[1693440],
    const REAL kminor_lower[64512],
    const REAL kminor_upper[44352],
    const int minor_limits_gpt_lower[64],
    const int minor_limits_gpt_upper[44],
    const BOOL minor_scales_with_density_lower[32],
    const BOOL minor_scales_with_density_upper[22],
    const BOOL scale_by_complement_lower[32],
    const BOOL scale_by_complement_upper[22],
    const int idx_minor_lower[32],
    const int idx_minor_upper[22],
    const int idx_minor_scaling_lower[32],
    const int idx_minor_scaling_upper[22],
    const int kminor_start_lower[32],
    const int kminor_start_upper[22],
    const BOOL tropo[5376],
    const REAL col_mix[107520],
    const REAL fmajor[430080],
    const REAL fminor[215040],
    const REAL play[5376],
    const REAL tlay[5376],
    const REAL col_gas[48384],
    const int jeta[107520],
    const int jtemp[5376],
    const int jpress[5376],
    REAL tau[1204224]);

void Planck_source(
    const int ncol,
    const int nlay,
    const int nbnd,
    const int ngpt,
    const int nflav,
    const int neta,
    const int npres,
    const int ntemp,
    const int nPlanckTemp,
    const REAL* tlay,
    const REAL* tlev,
    const REAL* tsfc,
    const int sfc_lay,
    const REAL* fmajor,
    const int* jeta,
    const BOOL* tropo,
    const int* jtemp,
    const int* jpress,
    const int* gpoint_bands,
    const int* band_lims_gpt,
    const REAL* pfracin,
    const REAL temp_ref_min,
    const REAL totplnk_delta,
    const REAL* totplnk,
    const int* gpoint_flavor,
    REAL* sfc_src,
    REAL* lay_src,
    REAL* lev_src_inc,
    REAL* lev_src_dec,
    REAL* sfc_src_jac);

} // namespace rrtmgp
